# Name of the workflow
name: Lint workflow

# Trigger the workflow on pull requests
on:
  pull_request:
    branches:
      - develop
      - staging
      - main

# jobs to run
jobs:
  test:
    runs-on: ubuntu-latest

    # steps in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run Build
        run: npm run build 

      - name: Run Tests
        run: npm run test
